### PR TITLE
Update strings.txt

### PR DESCRIPTION
**Pull request by Blackfiction**

### CODE REVIEW

**Comment by paul-1** [comment]
Please stop this, you are making a mess.  Do not create new branches for each commit.  Put them all in a single branch.   Then when you are done, then create the Pull Request in github.

What program are you using for git?

I took all of the PR's that Michael had not merged, and then made a branch on my git. https://github.com/paul-1/slimserver/tree/NL_Language_Updates  If you look at the commit, all of the files are listed in that commit.   Git is not really that bad, if you google what you are trying to do, there is alot of information out there.

**Comment by Blackfiction** [comment]
Sorry, I will try to update the remaining in one go. I was using the github website, Daan

**Comment by paul-1** [comment]
That would explain it, The Github website has limited tools for you to use online.  I only use the web site to make the final pull request.

Offline interfaces are much more powerful for git functions.  But if you don't use git much, The github website should have the option to just commit files to the current branch.   Work on your fork only.....then once you are happy, create the PR to the Logitech repo.  To save you some effort, I'll generate a PR on your git with everything you have done to right now.....merge that to your repo, then keep working.... in your 8.3 branch.

**Comment by Blackfiction** [comment]
Hi Paul and Michael,
I have changed some more nl strings for the plugins via github desktop (9 files). Should I push the ‘Commit to public 8.3’ button?
Thx, Daan.

***@***.***

**Comment by michaelherger** [comment]
I'd create a new branch to push the changes to. Because otherwise your 8.3 branch might get out of sync quickly.

**Pull request merged**
