### PR TITLE
Issue #1138 add all songs

### PR DESCRIPTION
**Pull request by darrell-k**

### CODE REVIEW

**Review by michaelherger — APPROVED** [review]
Wow! Great job! That looks amazingly simple 😃. Thanks!

**Comment by darrell-k** [comment]
Worth backporting to 8.5?

**Comment by michaelherger** [comment]
I'd rather concentrate on getting LMS 9 out the door... It's been broken forever, and nobody noticed before. It's not a big problem, is it?

**Comment by darrell-k** [comment]
Fair enough. When do you think 9.0 will be released? I would appreciate a few weeks notice so I can make sure outstanding requests on the works side are completed.

**Pull request merged**
