### PR TITLE
Updated as a part of the re-branding to Lyrion

### PR DESCRIPTION
**Pull request by JohanSaaw**
Exchanged the string squeezeboxserver with lyrionmusicserver in order to re-brand the product in RedHat.pm

This change must go together with the update I made to slimserver-platform. There is a pull request for that too.

### CODE REVIEW

**Review by michaelherger — APPROVED** [review]
Thanks a lot! Let's give this a try. And please stick around the forums to spot potential complaints 😉.

**Comment by JohanSaaw** [comment]
Hi,

Thanks. I will check. I am away as from today, so I will not be able to do any updates immediately. But I can check tje forum.

Johan

**Comment by michaelherger** [comment]
Oops... bad timing. I'll be leaving soon, too. But it'll be ok. Have a great time off!

**Comment by JohanSaaw** [comment]
Hi hope it will not be a problem. As I said, I will check the forum and try to help if there would be anything. Which threads do you think will be most likely to be used for an issue with the RPM?

Regardd Johan

**Pull request merged**
