### PR TITLE
delete keys and close handles in pipeline

### PR DESCRIPTION
**Pull request by philippe44**
This is what I would do for https://github.com/Logitech/slimserver/issues/475. Feel free to discard it if you don't like it

### CODE REVIEW

**Comment by michaelherger** [comment]
@bpa-code - I'd be happy to get your opinion on this. Thanks!

**Comment by paul-1** [comment]
Looks like you have an unrelated spelling error correction in this PR.   Otherwise looks ok.

**Comment by michaelherger** [comment]
> Looks like you have an unrelated spelling error correction in this PR. Otherwise looks ok.

I can take care of the typo :-). Other than that?

**Comment by paul-1** [comment]
Sorry, I edited my response.....it doesn't go through email.  That was the change I tested last night, although I don't understand how the STUFF_PIPE Label did anything, or is that why Phillip deleted that label.

**Comment by michaelherger** [comment]
I believe that's purely cosmetic. In the case of nested loops using labels can help to break out of an inner loop. But as we only have one loop here, it's not required.

**Comment by philippe44** [comment]
Yes, my understanding that is was not needed and I did not see the reason for "goto" labels and assigning $source to undef. I know I'm picky on these things as I always prefer less code to more code, hence I offered to not use that PR

**Pull request merged**
