### PR TITLE
Works menu for SB3

### PR DESCRIPTION
**Pull request by darrell-k**
A bit of an oversight!

### CODE REVIEW

**Comment by michaelherger** [comment]
How would I test this?...

**Comment by darrell-k** [comment]
You'd need an SB3. I do have one and it woks fine.

**Comment by michaelherger** [comment]
I'd have a SB3, Boom, SliMP3, Transporter, Softsqueeze 😉. But it wasn't clear immediately what it tried to resolve. Found the thread in the forums.

**Review by michaelherger — APPROVED** [review]

**Comment by darrell-k** [comment]
Ah yes, sorry, referencing the forum post might have helped!

**Pull request merged**
