### PR TITLE
Do not read tags from file while parsing embedded CUE to prevent recursion.

### PR DESCRIPTION
**Pull request by oleg-kuh**

### CODE REVIEW

**Comment by michaelherger** [comment]
Argh... a few minutes late... could you please rebase against latest 8.0?

**Comment by michaelherger** [comment]
Never mind. I re-applied your first PR with this one in addition. Seems to be working fine here. Let's see what others find... Thanks!

**Comment by terual** [comment]
Tested just now on my music collection and encountered no regressions (using 8.0.0 - 1604986877).

**Comment by StuartRob** [comment]
Same here with me.  Updated to the latest nightly (8.0.0 - 1604986877 @ Tue Nov 10) and scanning works again.

I'm happy to do testing but don't really know what to test or how, so any hints welcomed.

**Pull request closed without merging**
