### PR TITLE
Public/7.8

### PR DESCRIPTION
**Pull request by clivem**
Change LocalFile Protocol Handler behaviour to stream virtual tracks via http socket.

### CODE REVIEW

**Comment by mherger** [comment]
Clive - is there something wrong or should I really see your merges from our public/7.8 as part of your pull request again?

**Comment by clivem** [comment]
When I create a pull request, I'm not able to do it for a single commit. From your end, when you go to merge, can you choose to merge the single commit, rather than the commit and 2 merges?

**Comment by mherger** [comment]
Ok, I was able to cherry-pick that single change. Unfortunately I failed to figure out the command line myself, but sourcetree did the trick for me. Now if only it told me what exact magic it applied :-)

**Comment by mherger** [comment]
Clive - can we close this request?

**Pull request closed without merging**
