### PR TITLE
Fix artwork documentation to reflect the current state of code

### PR DESCRIPTION
**Pull request by terual**
See line https://github.com/LMS-Community/slimserver/blob/2315e3b4f305e526b11b02a34879040a76b86589/Slim/Music/Artwork.pm#L69 and https://github.com/LMS-Community/slimserver/blob/2315e3b4f305e526b11b02a34879040a76b86589/Slim/Music/Artwork.pm#L131

### CODE REVIEW

**Comment by michaelherger** [comment]
Thanks! But I think we should move this to lyrion.org, too. Like most/all of the documentation included in LMS itself.

**Comment by terual** [comment]
Good point, I will migrate the up-to-date parts when I have time. There are also some parts that are out-of-date according to the warnings on the page. What should we do with those parts?

**Comment by michaelherger** [comment]
Would you have a pointer for such an outdated part? It's time to clean up. There's no use migrating outdated stuff.

**Comment by terual** [comment]
This post by Daksol had already inventoried the parts that (according to the warnings) are outdated: https://forums.slimdevices.com/forum/developer-forums/developers/1668265-documentation-update-call-for-volunteers?p=1694219#post1694219

**Pull request merged**
