### PR TITLE
Fix Dutch spelling

### PR DESCRIPTION
**Pull request by terual**
- Fixes incorrect usage of spaces in compound words (see https://nl.wikipedia.org/wiki/Onjuist_spatiegebruik) (unfortunately this reverts a large part of 88f9937e2bfceb7457dfca914c759e46f5c0b62c....)
- Fixes incorrect capitalization of Dutch words
- Minor other fixes
- Change release type to uitgaventypes for Dutch

### CODE REVIEW

**Comment by michaelherger** [comment]
As the commit you mention was provided by @Blackfiction, I'd like to invite them to review this PR. Thanks!

**Comment by Blackfiction** [comment]
will be on holiday next week, but will review when I come back

**Comment by terual** [comment]
Perfect! And when you are at it, could you also weigh in on the discussion in https://github.com/LMS-Community/slimserver/pull/1061? Thanks!

**Review by Blackfiction — COMMENTED** [review]
I am ok with most of the changes but can we do;
release=release instead of uitgaventype. Nowadays everyone in NL knows what a release is and nobody knows what 'uitgaventype' is. Maybe we can improve some of the long words as well. Like, 'muziekspelerinstellingen' into 'instellingen van de muziekspeler'

**Comment by terual** [comment]
Agreed, I will update the PR the coming days with your suggestions.

**Comment by terual** [comment]
Because of merge conflicts I have created a new PR: https://github.com/LMS-Community/slimserver/pull/1085

**Pull request closed without merging**
