### PR TITLE
Don't use workId if it is -1

### PR DESCRIPTION
**Pull request by darrell-k**
While testing works search performance, noticed that I broke things in my last PR.

### CODE REVIEW

**Comment by michaelherger** [comment]
Thanks for that! Is there more to come?

**Comment by darrell-k** [comment]
I'm simplifying the SQL in worksQuery, certainly for the search, and looking into other improvements. That will be a separate PR, though.

**Comment by darrell-k** [comment]
What does the "Closed with unmerged commits" message mean?

**Comment by michaelherger** [comment]
Instead of asking you to remove the debug line and changing from `ne '-1'` to numerical `!= -1` I thought I'd let you concentrate on the other fixes and do this myself. I hope that's ok.

**Comment by darrell-k** [comment]
No problem. Thanks.

**Pull request closed without merging**
