### PR TITLE
More Audio Scan 1.05 module upgrades.

### PR DESCRIPTION
**Pull request by ralph-irving**

### CODE REVIEW

**Comment by michaelherger** [comment]
Did you want to add binaries, too? 😀

**Comment by ralph-irving** [comment]
Yes, that would help!

**Comment by mherger** [comment]
Thank you _very_ much! 

May I ask you what the motivation for this particular collection was? What would be typical representative distributions which would use these files?

**Comment by ralph-irving** [comment]
I already had VMs for the two intel updates for which we already had binaries and an SD card already loaded with the aarch64.

**Pull request merged**
