### PR TITLE
OPUS codec

### PR DESCRIPTION
**Pull request by philippe44**
This enables OPUS codec for clients that supports it. Patch for squeezelite to follow soon

### CODE REVIEW

**Comment by michaelherger** [comment]
No change?

**Comment by philippe44** [comment]
oh well ... works better with a  commit :-)

BTW, do you know why LMS does not try to look for a direct codec matching first? It seems that it takes the first thing that works, either this is a direct codec match or a transcoding rule. Of course, a transcoding rule often defeats the purpose of direct codec support if a codec with a transcoding rules appears first in the list.

**Comment by mherger** [comment]
Let's give this a try. Thanks!

**Comment by mherger** [comment]
BTW: are you going to change squeezelite etc., too? Or is this for SqueezeEsp only?

**Comment by philippe44** [comment]
I've changed squeezelite, I'll push a preliminary version

**Pull request merged**
