### PR TITLE
Correct start time for streams with range offset

### PR DESCRIPTION
**Pull request by philippe44**

### CODE REVIEW

**Comment by michaelherger** [comment]
Would you want to merge this to 8.2 or 8.3?

**Comment by philippe44** [comment]
It'd say 8.2 would be good - sorry

**Comment by mherger** [comment]
Ok, I rebased against 8.2, but now the previous change is part of this PR, too. Do you want both of them to be merged?

**Comment by philippe44** [comment]
Yes, that probably makes the most sense

**Pull request merged**
