### PR TITLE
Update faad helper binaries to fix a crash when the decoder call fails.

### PR DESCRIPTION
**Pull request by ralph-irving**
Fixes crash when parsing malformed AAC file in faad.
Reported in slimserver-vendor issue https://github.com/Logitech/slimserver-vendor/issues/95

### CODE REVIEW

**Review by michaelherger — COMMENTED** [review]
Did you leave out the Mac build on purpose?

**Comment by mherger** [comment]
Thanks a lot!

**Comment by ralph-irving** [comment]
I thought you added the new macos faad in commit de3a6719ec63449e3e2de50759d6917dc2e52132.  If not, let me know and I'll submit it.

**Comment by michaelherger** [comment]
I'm sorry for the misunderstanding. No worries: committed the binary you posted the other day on source forge, after removing i386.

**Pull request merged**
