### PR TITLE
fix(YAML): Add necessary .pm for the LibYAML upgrade to 0.65.

### PR DESCRIPTION
**Pull request by fsbruva**
Fixes server until the vendor buildme script is fixed.

### CODE REVIEW

**Comment by mherger** [comment]
Can't put the file there as it would conflict with the existing binaries.

**Comment by fsbruva** [comment]
I thought you built those modules with the build script changes (over in vendor) I authored for the move to Perl 5.26? I submitted this PR under the assumption  that YAML v 0.65 was used with that revised build script.

**Comment by mherger** [comment]
True, but they still seem to be 0.35. I never verified, tbh. But yesterday I checked the version on my build system, and it was old. I can double-check.

**Comment by fsbruva** [comment]
No worries. I was just trying to fix a potential oversight with my Perl 5.26 PR. Glad it was not needed.

**Pull request closed without merging**
