### PR TITLE
Use info instead of error log level for informative logging

### PR DESCRIPTION
**Pull request by RichieB2B**
Even with the log level set to `error` LMS is very chatty. This patch moves informative messages to log level `info`.
```
Nov  5 13:56:26 nasty squeezeboxserver[3945055]: [21-11-05 13:56:26.5543] main::main (206) Starting Logitech Media Server scanner (v8.3.0, 1635857800, Tue Nov  2 15:14:58 CET 2021) perl 5.028001
Nov  5 13:56:27 nasty squeezeboxserver[3945055]: [21-11-05 13:56:27.0184] Slim::Music::Import::runImporter (578) Starting Slim::Plugin::WiMP::Importer scan
Nov  5 13:56:27 nasty squeezeboxserver[3945055]: [21-11-05 13:56:27.5984] Slim::Music::Import::endImporter (711) Completed Slim::Plugin::WiMP::Importer Scan in 0.580 seconds.
Nov  5 13:56:27 nasty squeezeboxserver[3945055]: [21-11-05 13:56:27.5993] Slim::Music::Import::runImporter (578) Starting Plugins::Spotty::Importer scan
Nov  5 13:57:23 nasty squeezeboxserver[3945055]: [21-11-05 13:57:23.2652] Slim::Plugin::OnlineLibraryBase::deleteRemovedTracks (81) Get removed online tracks count
Nov  5 13:57:23 nasty squeezeboxserver[3945055]: [21-11-05 13:57:23.3764] Slim::Music::Import::endImporter (711) Completed Plugins::Spotty::Importer Scan in 55.777 seconds.
Nov  5 13:57:23 nasty squeezeboxserver[3945055]: [21-11-05 13:57:23.3768] Slim::Music::Import::runImporter (578) Starting Slim::Plugin::FullTextSearch::Plugin scan
Nov  5 13:57:23 nasty squeezeboxserver[3945055]: [21-11-05 13:57:23.3772] Slim::Plugin::FullTextSearch::Plugin::_rebuildIndex (475) Starting fulltext index build
Nov  5 13:57:23 nasty squeezeboxserver[3945055]: [21-11-05 13:57:23.3774] Slim::Plugin::FullTextSearch::Plugin::_rebuildIndex (479) Initialize fulltext table
Nov  5 13:57:23 nasty squeezeboxserver[3945055]: [21-11-05 13:57:23.6504] Slim::Plugin::FullTextSearch::Plugin::_rebuildIndex (492) Create fulltext index for tracks
Nov  5 13:57:33 nasty squeezeboxserver[3945055]: [21-11-05 13:57:33.3874] Slim::Plugin::FullTextSearch::Plugin::_rebuildIndex (502) Create fulltext index for albums
Nov  5 13:57:36 nasty squeezeboxserver[3945055]: [21-11-05 13:57:36.1004] Slim::Plugin::FullTextSearch::Plugin::_rebuildIndex (511) Create fulltext index for contributors
Nov  5 13:57:36 nasty squeezeboxserver[3945055]: [21-11-05 13:57:36.3270] Slim::Plugin::FullTextSearch::Plugin::_rebuildIndex (521) Create fulltext index for playlists
Nov  5 13:57:41 nasty squeezeboxserver[3945055]: [21-11-05 13:57:41.5448] Slim::Plugin::FullTextSearch::Plugin::_rebuildIndex (536) Optimize fulltext index
Nov  5 13:57:42 nasty squeezeboxserver[3945055]: [21-11-05 13:57:42.1506] Slim::Plugin::FullTextSearch::Plugin::_rebuildIndex (551) Fulltext index build done!
Nov  5 13:57:42 nasty squeezeboxserver[3945055]: [21-11-05 13:57:42.1507] Slim::Music::Import::endImporter (711) Completed Slim::Plugin::FullTextSearch::Plugin Scan in 18.774 seconds.
Nov  5 13:57:42 nasty squeezeboxserver[3945055]: [21-11-05 13:57:42.1508] Slim::Music::Import::runImporter (578) Starting Slim::Plugin::ExtendedBrowseModes::Libraries scan
Nov  5 13:57:42 nasty squeezeboxserver[3945055]: [21-11-05 13:57:42.1509] Slim::Music::Import::endImporter (711) Completed Slim::Plugin::ExtendedBrowseModes::Libraries Scan in 0.000 seconds.
Nov  5 13:57:42 nasty squeezeboxserver[3945055]: [21-11-05 13:57:42.1510] Slim::Music::Import::runImporter (578) Starting Slim::Plugin::OnlineLibrary::Importer::VirtualLibrariesCleanup scan
Nov  5 13:57:42 nasty squeezeboxserver[3945055]: [21-11-05 13:57:42.1687] Slim::Music::Import::endImporter (711) Completed Slim::Plugin::OnlineLibrary::Importer::VirtualLibrariesCleanup Scan in 0.018 seconds.
Nov  5 13:57:42 nasty squeezeboxserver[3945055]: [21-11-05 13:57:42.1696] Slim::Music::Artwork::updateStandaloneArtwork (234) Starting updateStandaloneArtwork for 0 albums
Nov  5 13:57:42 nasty squeezeboxserver[3945055]: [21-11-05 13:57:42.1697] Slim::Music::Import::endImporter (711) Completed updateStandaloneArtwork Scan in 0.001 seconds.
Nov  5 13:57:42 nasty squeezeboxserver[3945055]: [21-11-05 13:57:42.2820] Slim::Music::Artwork::precacheAllArtwork (657) Starting precacheArtwork for 7 albums
Nov  5 13:57:42 nasty squeezeboxserver[3945055]: [21-11-05 13:57:42.9438] Slim::Music::Artwork::__ANON__ (808) precacheArtwork finished in 0.659497976303101
Nov  5 13:57:42 nasty squeezeboxserver[3945055]: [21-11-05 13:57:42.9439] Slim::Music::Import::endImporter (711) Completed precacheArtwork Scan in 0.774 seconds.
Nov  5 13:57:42 nasty squeezeboxserver[3945055]: [21-11-05 13:57:42.9445] Slim::Music::Import::runScanPostProcessing (480) Starting Database optimization.
Nov  5 13:57:51 nasty squeezeboxserver[3945055]: [21-11-05 13:57:51.4232] Slim::Music::Import::endImporter (711) Completed dbOptimize Scan in 8.478 seconds.
```

### CODE REVIEW

**Comment by michaelherger** [comment]
Those log statements were created that way with a purpose. I don't think that 30 lines of log for a full scan are too chatty. In particular as the scanner.log is created anew with every scan. It's helpful information. Most people probably never look at that file, but for me it's super helpful to know that users having a problem can easily send me the most basic information I'd need to help them.

**Comment by RichieB2B** [comment]
The logging of the scan activity is very helpful. They are just not errors. If I want to see logging of normal behavior like scans I would set the log level of `scan` to `info`. What is the rational of logging these informative messages at the `error` level?

I am running [logcheck](https://packages.debian.org/stable/logcheck) on my log files because I want to be informed of problems. Not of scans that run successfully every hour. 

These messages are logged to `/var/log/daemon` by `journald`, not (just) to scanner.log

**Comment by RichieB2B** [comment]
Looking at the [scanner](https://github.com/Logitech/slimserver/blob/public/8.3/scanner.pl#L202) and [Slim::Utils::Log](https://github.com/Logitech/slimserver/blob/public/8.3/Slim/Utils/Log.pm#L1001) I wonder why the logging is also printed on stdout. Shouldn't that be turned off for the `server` category?

**Comment by mherger** [comment]
Please configure logcheck to ignore that file if it bothers you. As I outlined before the log level for these messages was likely set to `error` to just make sure we always get those messages in the log. I know this is semantically wrong. But let's be pragmatic here. This has been of great help for thousands of users, and doesn't bother 99.999...% of users who didn't need it so far. 

Thanks for your understanding.

**Comment by RichieB2B** [comment]
Sure, I see your point and logcheck is flexible enough. 

Do you know why Log4perl outputs both to scanner.log and stdout? Is that by design or a fluke? 

The reason I started "fixing" this is because the logs show up in /var/log/daemon now through journald. This did not used to happen with LMS 7.x

**Comment by mherger** [comment]
I'm not too familiar with Log4perl. As I've hardly ever touched that part of LMS I would be very much surprised if the behaviour changed from 7.x. Except if x < 7 😀 .

Maybe https://github.com/Logitech/slimserver/blob/a2ce3dda98606f46b668b8bc3abaee60ab65ad90/Slim/Utils/Log.pm#L166 would give you a hint?

**Comment by tomscytale** [comment]
the change in behaviour might be due to the migration to a systemd unit file instead of an init script

**Comment by RichieB2B** [comment]
It certainly is. LMS is not running with [--daemon ](https://github.com/Logitech/slimserver/blob/public/8.3/slimserver.pl#L841 )anymore, making Log4perl loading the `screen` output like @mherger pointed out. This makes systemd/journald store all logging in `/var/log/daemon`

I'm glad I found a bug in here after all.

```
squeeze+  867039  0.2  0.3 340500 247244 ?       Ss   Nov05  13:10 /usr/bin/perl /usr/sbin/squeezeboxserver /usr/sbin/squeezeboxserver /usr/sbin/squeezeboxserver --prefsdir /var/lib/squeezeboxserver/prefs --logdir /var/log/squeezeboxserver/ --cachedir /var/lib/squeezeboxserver/cache --charset utf8
```

The [systemd service](https://github.com/Logitech/slimserver-platforms/blob/public/8.3/debian/logitechmediaserver.service) file uses `Type=simple` without `--daemon` where `Type=forking` with `--daemon` might be more appropriate.

**Comment by RichieB2B** [comment]
> https://github.com/Logitech/slimserver/blob/a2ce3dda98606f46b668b8bc3abaee60ab65ad90/Slim/Utils/Log.pm#L166

Should't be `&&` instead of `||` ? This way adding only `--quiet` doesn't make the condition true. :-(

It turns out that not loading `screen` in log4perl is not enough. It is the closing of STDOUT that does the trick:

https://github.com/Logitech/slimserver/blob/a2ce3dda98606f46b668b8bc3abaee60ab65ad90/slimserver.pl#L976

I've pushed a fix in #696

**Pull request closed without merging**
