### PR TITLE
Update strings.txt

### PR DESCRIPTION
**Pull request by Blackfiction**

### CODE REVIEW

**Comment by michaelherger** [comment]
Why don't you submit one single PR instead one each for each file modified?...

**Comment by Blackfiction** [comment]
Sorry, don’t know how to submit 1 for multiple files…

**Comment by michaelherger** [comment]
Just edit all the files, push them all to the same branch instead of each one individually. Then submit a PR.

**Comment by Blackfiction** [comment]
Ok, will try tomorrow!

**Pull request merged**
