### PR TITLE
Synology fix for UTF-8

### PR DESCRIPTION
**Pull request by ghost**
Synology added a fix for UTF-8 support in their packages for the Synology nas running the latest DSM6. It would be helpful to add this patch to the Synology.pm here.
See thread: http://forums.slimdevices.com/showthread.php?103636-Test-Repo-for-LMS-7-9-0-on-Synology-DSM-5-*&p=852112&viewfull=1#post852112

### CODE REVIEW

**Comment by mherger** [comment]
Thanks!

**Comment by ghost** [comment]
Thank you! 

Saves me a bit of work ;-)

Greetings,

Martin

Op 3 mei 2016 08:32, bij 08:32, mherger notifications@github.com schreef:

**Comment by mherger** [comment]
Would you have more patches which can be applied to the core code?

**Comment by ghost** [comment]
Hi Michael,

Thanks for asking.  I don' t think I have, but to be honest, I didn't went
through the DSM6 code yet that thorougly. I' ll let you know if  there is
more specific Synology code.

Thanks again,

Martin
Op 3 mei 2016 3:16 p.m. schreef "mherger" notifications@github.com:

**Pull request merged**
