### PR TITLE
Add composer, conductor and jazz composer icons to ExtendedBrowseMode…

### PR DESCRIPTION
**Pull request by terual**
…s plugin

### CODE REVIEW

**Review by michaelherger — APPROVED** [review]
Nice one! Where's the template? 😁 

Thanks!

**Comment by terual** [comment]
It's here: https://github.com/LMS-Community/lms-community.github.io/commit/54ee726a33448f27b974d0b2945c7b1d92bb6d02

It needs some explanation how to use it, so I think I have to create some sort of page under reference with some instructions.

**Comment by michaelherger** [comment]
Oh wow... I thought I'd quickly install Inkscape... but that's a different world! I have no idea how that works 🤦🏻.

**Comment by terual** [comment]
If you need more icons just let me know :smiley:

**Pull request merged**
