### PR TITLE
Add Perl 5.24 binaries for arm

### PR DESCRIPTION
**Pull request by paul-1**
Binaries that were built for a Raspberry Pi armv6 processor

### CODE REVIEW

**Comment by mherger** [comment]
Thanks Paul! Would you know any OS I could test this easily with on a Pi (besides pCP)? I don't want to spend hours installing...

**Comment by paul-1** [comment]
I thought about the same thing.  Probably the easiest way would be to install Raspbian, and then use perlbrew to install a non-standard perl.....   but that still takes hours.    I think Debian Stretch is the the only OS using 5.24, and RPI images are not out yet.     Arch linux is already on perl 5.26

**Comment by paul-1** [comment]
Looks like some have been successful upgrading Rasbian Jesse Lite to Stretch.   I'll give that a try an test the binaries there.

**Comment by paul-1** [comment]
Using a rpi B+, I upgraded to stretch, there was a lot of manual package installation, but I made sure I was running perl 5.24 and glibc2.24.  Cloned 7.9.1 from my github repo.   Server started fine with no command line arguments.  I connected a player, played some streams, and scanned my full media library with no problems.  Do you have any other specific tests that you run?

Logitech Media Server Version: 7.9.1 - git-1d90c6c @ 2017-06-25 11:56:42 -0400
Hostname: stretch
Server IP Address: 192.168.0.19
Server HTTP Port Number: 9000
Operating system: Debian - EN - utf8
Platform Architecture: armv7l-linux
Perl Version: 5.24.1 - arm-linux-gnueabihf-thread-multi-64int
Audio::Scan: 0.95
Database Version: DBD::SQLite 1.34_01 (sqlite 3.7.7.1)
Total Players Recognized: 1

**Comment by mherger** [comment]
Thanks, did the same :-). Takes ages on the B+...

**Pull request merged**
