### PR TITLE
Add arch for perl 5.28 and x86_64 binaries

### PR DESCRIPTION
**Pull request by paul-1**
Perl 5.28 is out, figured I would get this built.

```
Logitech Media Server Version: 7.9.2 - git-69f87c47d @ 2018-07-03 22:42:45 -0400
Hostname: NUC-Devel
Server IP Address: 192.168.0.141
Server HTTP Port Number: 9000
Operating system: Debian - EN - utf8
Platform Architecture: x86_64-linux
Perl Version: 5.28.0 - x86_64-linux-thread-multi
Audio::Scan: 0.95
IO::Socket::SSL: 2.056
Database Version: DBD::SQLite 1.34_01 (sqlite 3.7.7.1)
Total Players Recognized: 8.
```

### CODE REVIEW

**Comment by mherger** [comment]
Thanks @paul-1! What would be a distribution to test this with?

**Comment by paul-1** [comment]
Not aware of a distro using it yet, but I would bet it won’t be long.  I run a custom Perl on my Ubuntu system just for LMS.   These were built on Ubuntu 16.04.

**Comment by mherger** [comment]
Thanks! I'll wait for a system to require this and will be happy to test and merge then.

**Comment by oneplusme** [comment]
Fedora 29 is shipping with perl 5.28.  I've merged this locally and it seems to be working fine.

**Comment by michaelherger** [comment]
@paul-1 would you mind compiling the latest for Audio::Scan and DBD::SQLite?

**Comment by paul-1** [comment]
Sure thing.

**Comment by paul-1** [comment]
Upgraded to Audio::Scan 1.02 and DBD::SQLite 1.58

@oneplusme would you mind testing out the latest commits.

**Comment by michaelherger** [comment]
@paul-1 odd one: most modules load successfully, but `EV` doesn't:

```Loaded module: [version] ok!
Loaded module: [Time::HiRes] ok!
Loaded module: [DBI] ok!
Module [EV] failed to load:
Can't load '/home/mh/git/slimserver/CPAN/arch/5.28/x86_64-linux-thread-multi/auto/EV/EV.so' for module EV: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /home/mh/git/slimserver/CPAN/arch/5.28/x86_64-linux-thread-multi/auto/EV/EV.so) at /home/mh/perl5/perlbrew/perls/perl-5.28.0/lib/5.28.0/x86_64-linux-thread-multi/DynaLoader.pm line 193.
 at /home/mh/git/slimserver/CPAN/EV.pm line 127.
BEGIN failed--compilation aborted at /home/mh/git/slimserver/CPAN/EV.pm line 127.
Compilation failed in require at (eval 16) line 1.
BEGIN failed--compilation aborted at (eval 16) line 1.

Removing [common::sense] from the symbol table - load failed.
Removing [EV] from the symbol table - load failed.
Loaded module: [XML::Parser::Expat] ok!
Loaded module: [HTML::Parser] ok!
Loaded module: [JSON::XS] ok!
Loaded module: [Digest::SHA1] ok!
Loaded module: [YAML::XS] ok!
Loaded module: [Sub::Name] ok!
```

Tested this on a not fully updated Debian, using Perlbrew.

**Comment by mherger** [comment]
Thanks @paul-1 . Support for 5.28 is now in. Please give it a try.

**Comment by mherger** [comment]
5.28 now is in. Please give it a try. Thanks!

**Comment by oneplusme** [comment]
@mherger @paul-1 Working for me. Thanks!

**Comment by paul-1** [comment]
One thing I can think of is that I compiled this on my Ubuntu 18.10 which comes with glibc v 2.28.

According to the notes, Fedora 29 was supposed to have that version of glibc, so I went with it.  I would think any OS releasing with Perl 5.28 from this point forward would also upgrade glibc........

**Pull request closed without merging**
